name: Wait for check name
on:
  pull_request: {}

jobs:
  wait-for-check-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Wait on tests
        uses: ./
        with:
          ref: ${{ github.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10 # seconds
          running-workflow-name: wait-for-check-name
          check-name: build

      - name: Success
        run: echo 'Success!'