name: Build Status

on: 
  workflow_run:
    workflows: ['build']
    types:
      - completed
jobs:
  on-completed:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: exit 0
      - if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: exit 1
